- name: Check if kublet is configured
  ansible.builtin.stat:
    path: "/etc/kubernetes/kubelet.conf"
  register: kubelet_configured

- name: Join k8s cluster
  ansible.builtin.include_tasks: k8s_join.yml
  when: "kubernetes.cluster.kubeadm.force_reset or not kubelet_configured.stat.exists"
