- name: Get kubernetes release signing key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v{{ kubernetes.patch_version }}/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    mode: '0644'
  become: true
  check_mode: false

- name: Add in apt source for k8s
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes.patch_version }}/deb/ /'
    state: present
    filename: 'kubernetes'
    update_cache: true
  become: true
  check_mode: false
