host:
  temp_directory: "/tmp/ansible_home"
  network:
    dns_nameservers:
      - "75.75.75.75"
      - "75.75.76.76"
  patching:
    enabled: false
    cron: ['15', '2', '*', '*', '1'] # 2:15 AM every Monday
