- name: Copy containerd config file
  ansible.builtin.template:
    src: containerd_config.toml.j2
    dest: /etc/containerd/config.toml
    mode: "0644"
  become: true
  notify: restart_containerd

- name: Load dependent kernel modules
  ansible.builtin.modprobe:
    name: "{{ item }}"
    persistent: "present"
    state: "present"
  loop:
    - overlay
    - br_netfilter
  become: true
