- name: Copy containerd config file
  ansible.builtin.template:
    src: containerd_config.toml.j2
    dest: /etc/containerd/config.toml
    mode: "0644"
  become: true
  notify: restart_containerd

- name: Copy containerd modules file
  ansible.builtin.template:
    src: containerd_modules.conf.j2
    dest: /etc/modules-load.d/containerd.conf
    mode: "0644"
  become: true
  notify: restart_containerd
