- name: Get docker release signing key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker-apt-keyring.gpg
    mode: '0644'
  become: true
  check_mode: false

- name: Debug values
  ansible.builtin.debug:
    msg:
      - "Architecture: {{ ansible_architecture }}"
      - "Distribution Release: {{ ansible_distribution_release }}"

- name: Add in apt source for docker
  ansible.builtin.apt_repository:
    repo: 'deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker-apt-keyring.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable'
    state: present
    filename: 'docker'
    update_cache: true
  become: true
  check_mode: false
