- name: Configure cgroups
  ansible.builtin.include_tasks: configure_cgroups.yml

- name: Configure networking
  ansible.builtin.include_tasks: configure_networking.yml

- name: Configure swap
  ansible.builtin.include_tasks: configure_swap.yml
